// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Zoo.Infrastructure;

#nullable disable

namespace Zoo.Infrastructure.Migrations
{
    [DbContext(typeof(ZooContext))]
    [Migration("20260910140909_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Zoo.Infrastructure.Models.AnimalDetailModel", b =>
                {
                    b.Property<Guid>("AnimalId")
                        .HasColumnType("uuid");

                    b.Property<string>("MedicalNotes")
                        .HasColumnType("text");

                    b.HasKey("AnimalId");

                    b.ToTable("AnimalDetails");
                });

            modelBuilder.Entity("Zoo.Infrastructure.Models.AnimalModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<Guid?>("EnclosureId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Species")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EnclosureId");

                    b.ToTable("Animals", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Zoo.Infrastructure.Models.EnclosureModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Area")
                        .HasColumnType("double precision");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Enclosures");
                });

            modelBuilder.Entity("Zoo.Infrastructure.Models.BirdModel", b =>
                {
                    b.HasBaseType("Zoo.Infrastructure.Models.AnimalModel");

                    b.Property<bool>("CanFly")
                        .HasColumnType("boolean");

                    b.Property<string>("FeatherColor")
                        .HasColumnType("text");

                    b.Property<double>("Wingspan")
                        .HasColumnType("double precision");

                    b.ToTable("Birds", (string)null);
                });

            modelBuilder.Entity("Zoo.Infrastructure.Models.MammalModel", b =>
                {
                    b.HasBaseType("Zoo.Infrastructure.Models.AnimalModel");

                    b.Property<string>("Diet")
                        .HasColumnType("text");

                    b.Property<string>("FurColor")
                        .HasColumnType("text");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.ToTable("Mammals", (string)null);
                });

            modelBuilder.Entity("Zoo.Infrastructure.Models.AnimalDetailModel", b =>
                {
                    b.HasOne("Zoo.Infrastructure.Models.AnimalModel", "Animal")
                        .WithOne("Detail")
                        .HasForeignKey("Zoo.Infrastructure.Models.AnimalDetailModel", "AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("Zoo.Infrastructure.Models.AnimalModel", b =>
                {
                    b.HasOne("Zoo.Infrastructure.Models.EnclosureModel", "Enclosure")
                        .WithMany("Animals")
                        .HasForeignKey("EnclosureId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Enclosure");
                });

            modelBuilder.Entity("Zoo.Infrastructure.Models.BirdModel", b =>
                {
                    b.HasOne("Zoo.Infrastructure.Models.AnimalModel", null)
                        .WithOne()
                        .HasForeignKey("Zoo.Infrastructure.Models.BirdModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Zoo.Infrastructure.Models.MammalModel", b =>
                {
                    b.HasOne("Zoo.Infrastructure.Models.AnimalModel", null)
                        .WithOne()
                        .HasForeignKey("Zoo.Infrastructure.Models.MammalModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Zoo.Infrastructure.Models.AnimalModel", b =>
                {
                    b.Navigation("Detail");
                });

            modelBuilder.Entity("Zoo.Infrastructure.Models.EnclosureModel", b =>
                {
                    b.Navigation("Animals");
                });
#pragma warning restore 612, 618
        }
    }
}
